Completing, refactoring and improving the `WITH` statements parser
phpmyadmin/sql-parser pull request #363
Opened 2021-12-05 22:43 UTC by iifawzi

Hi, this PR is completing https://github.com/phpmyadmin/sql-parser/pull/334#issuecomment-986011386 and fixing https://github.com/phpmyadmin/sql-parser/issues/353.

I've targeted the Master branch,  because I couldn't find the `WithStatement` parser in the QA branch, which's weird. 
Anyway, I've re-designed the `WITH` parser to be able to catch and throw more appropriate errors, and made the `Create` and `Insert` statements aware of it.

I've Added a bunch of comments, because there were some complex operations/decisions, hopefully to help us in the future if we wanted to modify anything, let me know if there's anything unclear. I've also added as much tests as I could.

2021-12-05 23:13 UTC, iifawzi commented
working on fixing the tests issues.

2021-12-06 00:20 UTC, williamdes commented on src/Statements/CreateStatement.php
> +            if ($this->select) {
```suggestion
            if ($this->select !== null) {
```

2021-12-06 00:20 UTC, williamdes commented on src/Statements/CreateStatement.php
> +            } elseif ($this->with) {
```suggestion
            } elseif ($this->with !== null) {
```

2021-12-06 00:21 UTC, williamdes commented on src/Statements/InsertStatement.php
> +                    $this->select = new WithStatement($parser, $list);
```suggestion
                    $this->with = new WithStatement($parser, $list);
```

Like phpstan says ?

2021-12-06 02:36 UTC, mauriciofauth requested changes

2021-12-06 02:36 UTC, mauriciofauth commented on tests/Builder/CreateStatementTest.php
> +        // );
You forgot this commented code here.

2021-12-06 02:36 UTC, mauriciofauth commented on tests/Builder/CreateStatementTest.php
> +        // );
You forgot this commented code here.

2021-12-06 06:39 UTC, iifawzi commented on tests/Builder/CreateStatementTest.php
> +        // );
My bad, thank you, resolved.

2021-12-07 00:09 UTC, williamdes commented on tests/Parser/WithStatementTest.php
> -        $this->assertEquals('SELECT * FROM categories', $parser->statements[1]->build());
why was this needed to be removed ?

2021-12-07 07:07 UTC, iifawzi commented on tests/Parser/WithStatementTest.php
> -        $this->assertEquals('SELECT * FROM categories', $parser->statements[1]->build());
Hi, This's removed because, previously the Parser with dealing with the CTE expression as a separate statement, that's why we had two statements. Now, the CTE is included within the WITH statement, so it's a single statement that contain both. 

That's being said, the CTE statement should exist in the first statement, which isn't happening now. 
```SQL
$expected = <<<SQL
WITH categories(identifier, name, parent_id) AS (SELECT c.identifier, c.name, c.parent_id FROM category AS `c` WHERE c.identifier = 'a' UNION ALL SELECT c.identifier, c.name, c.parent_id FROM categories, category AS `c` WHERE c.identifier = categories.parent_id), foo AS (SELECT * FROM test)
SQL;
```

I will work on it. I'd need to change the structure of the `withKeyword` a little bit.

2021-12-07 08:17 UTC, iifawzi commented on src/Statements/WithStatement.php
> +
Now, the CTE statement will be built and appended to the end of the `WithStatements` after building all `withers`

2021-12-07 08:17 UTC, iifawzi commented on tests/Parser/WithStatementTest.php
>          $this->assertEquals($expected, $parser->statements[0]->build());
Thus, it's only a one statement that contains the withers and the CTE.

2021-12-07 08:21 UTC, iifawzi commented
Regarding psalm, it's complaining because the property `$cteStatementParser` is not set in the constructor. 
I don't know how to surpass this, except using ``` /** @psalm-suppress PropertyNotSetInConstructor */ ```
@williamdes

2021-12-11 09:21 UTC, williamdes commented on src/Statements/CreateStatement.php
> +                $builtStatement = $this->select->build();
do you know why it is reported non covered ?

2021-12-11 09:24 UTC, williamdes approved these changes
This is really awesome ! :100:
Let me know when this is finished for a final review :)

2021-12-11 11:26 UTC, iifawzi commented on src/Statements/CreateStatement.php
> +                $builtStatement = $this->select->build();
After 2 hours of investigation, It seems like it was always reporting false positive. it's A separate bug not related to the changes proposed in this PR,  but it's now shown as uncovered because previously it wasn't in a separate branch: 
https://github.com/phpmyadmin/sql-parser/blob/ed0b4ba26ebcee7194652bd830d525084aefc21e/src/Statements/CreateStatement.php#L468-L471

The bug seems to be coming from this portion of code: 
https://github.com/phpmyadmin/sql-parser/blob/ed0b4ba26ebcee7194652bd830d525084aefc21e/src/Statements/CreateStatement.php#L699-L718

You will notice that after parsing the array options if exists, we update the `$list->idx` by these two lines of code: 
```PHP 
 ++$list->idx; // Skipping last token from the array. 
$list->getNext(); 
```
and that's totally fine, the issue is that in the code that follows, we're checking the `$token` in its old state, which was set before updating the index.

I will try to find sometime to fix it, next weeks, but it has nothing to do with this PR.

2021-12-11 11:41 UTC, iifawzi commented
I've just noticed a test that I've duplicated by mistake, removed.
It's now totally finished :')

2021-12-29 14:34 UTC, mauriciofauth approved these changes

2021-12-29 14:35 UTC, merged

2021-12-29 14:35 UTC, mauriciofauth commented
Merged, thanks for your contribution!