feat: Implementing and refactoring the KILL statement parser
phpmyadmin/sql-parser pull request #565
Opened 2024-07-09 21:39 UTC by iifawzi

2024-07-10 07:44 UTC, kamil-tekiela requested changes

2024-07-10 07:44 UTC, kamil-tekiela commented on .gitignore
> +**/.DS_Store
This doesn't look like it should be part of this pr

2024-07-10 07:44 UTC, kamil-tekiela commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
Why are the property types missing? Can you please add all of them?

2024-07-10 07:44 UTC, kamil-tekiela commented on src/Statements/KillStatement.php
> +                        if (count($subParser->errors)) {
Please don't use count() as a Boolean value. Use strict array comparison. !== []

What exactly is the purpose of this if statement though?

2024-07-10 07:44 UTC, kamil-tekiela commented on src/Statements/KillStatement.php
> +        if ($this->options && count($this->options->options) > 0) {
`$this->options` is not a Boolean. Please add the condition. And same as above please don't use count as a Boolean.

2024-07-10 07:44 UTC, kamil-tekiela commented on src/Statements/KillStatement.php
> +        $builtIdentifier = (string) $this->identifier;
Isn't this the same as the code in the if statement below?

2024-07-10 07:48 UTC, iifawzi commented on .gitignore
> +**/.DS_Store
it isn't worth it to be in a separate PR. what do you think?

2024-07-10 07:48 UTC, iifawzi commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
phpstan complains about the php7 support. should we add it and update the baseline?

2024-07-10 07:52 UTC, iifawzi commented on src/Statements/KillStatement.php
> +                        if (count($subParser->errors)) {
sure, way more performant. thanks for the suggestion. 
checking the errors of subparser is needed so we can throw them. do u have better ways in mind?

2024-07-10 07:54 UTC, kamil-tekiela commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
@MauricioFauth what is the minimum version of PHP? Is it 7.2?

2024-07-10 07:57 UTC, iifawzi commented on src/Statements/KillStatement.php
> +        $builtIdentifier = (string) $this->identifier;
Indeed, I didn't notice that `Statement` implements`__toString`

2024-07-10 07:59 UTC, iifawzi commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
interestingly, in `5.10.x` it's 7.2 yes. but in the main, it's 8.1..

2024-07-10 08:00 UTC, iifawzi commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
I might have forgotten how we do releases, shouldn't 5.10.x be the upcoming version? how it supports 7.2 and main isn't?

2024-07-10 08:52 UTC, williamdes commented on tests/data/parser/parseKill2.out
> +                    "@type": "PhpMyAdmin\\SqlParser\\Statements\\SelectStatement",
I am not sure what to pick
Can you share a diff or something more explicit to help choosing ?

2024-07-10 09:21 UTC, iifawzi commented on tests/data/parser/parseKill2.out
> +                    "@type": "PhpMyAdmin\\SqlParser\\Statements\\SelectStatement",
it's either the built statement: 
```
  "identifier": "SELECT 3 + 4",
``
or the statement object ( Select Statement ) as committed in the file

2024-07-10 09:26 UTC, kamil-tekiela commented
DS_Store are MacOS files so they are not relevant to this project. They should not be ignored at all. You can ignore them locally on your machine.

2024-07-10 09:33 UTC, iifawzi commented
it's easier for future contributors to have it ignored by the repo, like we do with .idea files.

2024-07-10 16:58 UTC, MauricioFauth commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
The version 5.x of sql-parser are used by phpMyAdmin 5.2.x, that's why it requires PHP 7.2, the `master` branch is for sql-parser 6.x, which is used by phpMyAdmin 6.0.x.

2024-07-11 09:52 UTC, williamdes commented on tests/data/parser/parseKill2.out
> +                    "@type": "PhpMyAdmin\\SqlParser\\Statements\\SelectStatement",
I think Select Statement has better parsing for many possible syntaxes
And it can be ->toString() that should equal to the old data ("identifier") ?

2024-07-11 09:53 UTC, williamdes commented on src/Statements/KillStatement.php
> +    public $IDKeywordUsed = false;
yes, or the merge user can add them at merge time

2024-07-11 09:55 UTC, williamdes commented
> DS_Store are MacOS files so they are not relevant to this project. They should not be ignored at all. You can ignore them locally on your machine.

I checked, and yes I think the actual consensus is to remove them locally. We do not have it in any repo.

Ref: https://github.com/phpmyadmin/phpmyadmin/issues/15903#issuecomment-581431150
Can you remove the commit ?

2024-07-11 10:54 UTC, iifawzi commented on tests/data/parser/parseKill2.out
> +                    "@type": "PhpMyAdmin\\SqlParser\\Statements\\SelectStatement",
Yes, exactly.

2024-07-12 00:10 UTC, MauricioFauth commented on src/Parser.php
> -            'class' => 'PhpMyAdmin\\SqlParser\\Components\\Expression',
I think creating a `PhpMyAdmin\SqlParser\Components\KillKeyword` class will be better than overriding `Statement::parse()`.

2024-07-12 00:55 UTC, iifawzi commented on src/Parser.php
> -            'class' => 'PhpMyAdmin\\SqlParser\\Components\\Expression',
Yes, that can certainly be done, and we can rely on the clauses to have it parsed. Correct me if you meant another way.

https://github.com/phpmyadmin/sql-parser/blob/417ad4cf2eaa13d61dfd67dacf0458c9b586be5d/src/Statement.php#L263-L274

I just believe that components should be used for parts that are common across multiple query statements, which aligns with the current behavior of our components. What do you think? In my opinion, "KILL" is a statement and shouldn't be identified as a keyword.

Given this discussion, I think conventions have become mixed over the years. That's why I would really appreciate everyone's participation in this discussion to ensure consistency moving forward.

2024-07-14 20:27 UTC, MauricioFauth commented on src/Parser.php
> -            'class' => 'PhpMyAdmin\\SqlParser\\Components\\Expression',
> I just believe that components should be used for parts that are common across multiple query statements

That makes sense.

2024-07-14 20:27 UTC, MauricioFauth approved these changes

2024-07-15 12:21 UTC, williamdes commented on src/Statements/KillStatement.php
> +     * @psalm-var bool
```suggestion
     * @var bool
```

2024-08-07 13:53 UTC, niconoe- approved these changes
For what it worth, LGTM.

2024-08-26 11:16 UTC, merged